# Generated by Django 4.1.1 on 2022-10-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=50)),
                ('join_date', models.DateTimeField()),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('telephones', models.JSONField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'emprendimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('images_url', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateTimeField()),
                ('join_date', models.DateTimeField()),
                ('role', models.CharField(max_length=20)),
                ('authorities', models.JSONField(blank=True, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('last_login_date_display', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_not_loked', models.BooleanField(blank=True, null=True)),
                ('emp_liked', models.TextField(null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
