# Generated by Django 4.1.1 on 2022-11-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateTimeField()),
                ('join_date', models.DateTimeField()),
                ('role', models.CharField(max_length=20)),
                ('authorities', models.JSONField(blank=True, null=True)),
                ('profile_image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('last_login_date_display', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_not_loked', models.BooleanField(blank=True, null=True)),
                ('liked', models.CharField(blank=True, max_length=500, null=True)),
                ('likedd', models.JSONField(blank=True, null=True)),
                ('favorite_emprendimientos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user2',
                'managed': False,
            },
        ),
    ]
